### ISSUE TITLE
Wrong number of totalServers?

### ISSUE THREAD

**Issue by volcanofr** [discordexperimenthub/assyst-tags#2]
According to Discord, there is [19 Million active servers per week](https://discord.com/company). But in [line 179 of `experiment-rollout.js`](https://github.com/discordexperimenthub/assyst-tags/blob/main/experiment-rollout.js#LL179C31-L179C31) there is only 6.7 Million total guilds.

**Comment by Tolga1452** [comment]
Oh yes seems my sources are old. Also total users are wrong too iirc

**Comment by Tolga1452** [comment]
fixed
