### ISSUE TITLE
Suggestion: Automatically detect tag name.

### ISSUE THREAD

**Issue by qwertyad1** [discordexperimenthub/assyst-tags#26]
Instead of having the tag creator input the tag as the first function argument, you can use `message.content.split(" ")[1]` to extract the tag name directly.
edit: here is an example: ![Screenshot_20230531-215454](https://github.com/discordexperimenthub/assyst-tags/assets/64162703/b75f6687-3c14-4013-9907-9669ce32579e)

**Comment by qwertykid** [comment]
image for context:
![Uploading Screenshot_20230531-214839.png…]()

**Comment by Tolga1452** [comment]
Oh right. Thanks for the suggestion!
