### ISSUE TITLE
Pomelo started rolling out for normal users!

### ISSUE THREAD

**Issue by n-xsi** [discordexperimenthub/assyst-tags#28]
Status should be 2 now in [here](https://github.com/discordexperimenthub/assyst-tags/blob/main/experiment-rollout.js#L64)

Image:
![image](https://github.com/discordexperimenthub/assyst-tags/assets/78408288/3a713845-e2d2-46a5-8662-cc904b536d27)

**Comment by Tolga1452** [comment]
> Status should be 2 now in [here](https://github.com/discordexperimenthub/assyst-tags/blob/main/experiment-rollout.js#L64)

Rollout did not complete yet, so it should be `1`
