### ISSUE TITLE
Pomelo rollout still mentions large bots 😡😡

### ISSUE THREAD

**Issue by Lordcobcob** [discordexperimenthub/assyst-tags#31]
This is clearly an old line as now we all know that bots aren't getting the update so cant you just like fix the code and make it so that it says the right thing as seen as this is a PUBLIC tag 😤😡😡😡 Like SERIOUSLY tolg stop spreading misinformation and FIX THIS ISSUE. /j /j this is all a joke but srsly there is an issue where it still mentions large bots lol  
> :check:  Brands / Large bots

seen in this line pls fix

**Comment by Tolga1452** [comment]
cuz they're reversed to prevent scams
