### ISSUE TITLE
Update pomelo roleout stats

### ISSUE THREAD

**Issue by purpledalek** [discordexperimenthub/assyst-tags#35]
Please update pomelo roleout stats

**Comment by Tolga1452** [comment]
What's the missing data?

**Comment by purpledalek** [comment]
Ah, my bad, meant to put pomelo data, as there's been roleouts that go up to (I believe) the 15th of June, and the bot still says the last roleout was until the 9th

**Comment by Tolga1452** [comment]
There are more than one unofficial resources with different stats so we can't change them. You can use the #pomelo-reports channel in [our server](https://discord.gg/experiments) to report anything you saw about pomelo
