### ISSUE TITLE
Markdown user isn't release for me on canary 

### ISSUE THREAD

**Issue by Soulivan71** [discordexperimenthub/assyst-tags#38]
![image](https://github.com/discordexperimenthub/assyst-tags/assets/36502190/f36ae0a9-0909-46c0-9de3-a50e1bd02e38)
![image](https://github.com/discordexperimenthub/assyst-tags/assets/36502190/b86bfce8-42e5-4b72-94d8-800b5506ce71)

Like # and - I can't see

**Comment by Zyrenth** [comment]
Have you messed with the markdown experiments before? Such as enabling/disabling the experiment manually?
If you did I suggest resetting the local storage and cache completely through devtools.
And if that still did not help I suggest disabling custom themes or plugins to check if that helps.

Also, could you check this in the browser if it works there, it means that it rolled out to you.
(Btw this isn't really related to assyst tags but I'm happy to help you here.)

**Comment by Soulivan71** [comment]
Have you messed with the markdown experiments before? Such as
enabling/disabling the experiment manually?
-> No
 And if that still did not help I suggest disabling custom themes or
plugins to check if that helps.
-> I already tried, and Im still having issue after disable and reloading
the app

**Comment by Zyrenth** [comment]
Does it work on discord web? If yes you could try reinstalling your discord client (or if you want to avoid that for now you can install another release of the client. Download for [Windows](https://discord.com/api/downloads/distributions/app/installers/latest?channel=canary&platform=win&arch=x86) or [Linux](https://discord.com/api/download/canary?platform=linux&format=deb))

**Comment by Soulivan71** [comment]
I don't want help. Im just giving the information.

**Comment by Zyrenth** [comment]
Any reason on reopening this issue? You said you don't need help.
